from __future__ import annotations

from dataclasses import dataclass
import logging
import ast
from pathlib import Path
from typing import Any, Iterable, List, Optional, Tuple
from lark import Token, UnexpectedInput, v_args
from symphony import (
    Diagnostic,
    DiagnosticBag,
    DiagnosticLabel,
    DiagnosticSeverity,
    SourcePosition,
    SymphonyDiagnosticsException,
    SymphonyFiles,
    errors,
    report_diagnostics,
    symphony_position,
)
from symphony.abstract_syntax_tree import (
    DimensionDeclaration,
    Modules,
    AnyDeclaration,
    MemberDeclaration,
    CategoryDeclaration,
    Module,
    TypedList,
    StringWithPosition,
)
from symphony.base_transformer import BaseTransformer
from symphony.loader import Loader, LoaderResult

# Builds the Pass 1 parser and transformer for Symphony.
# It loads the packaged grammar, parses the model declaration into a Lark parse tree,
# and produces a raw abstract syntax tree without semantic validation; later passes
# handle ordering and cross-reference checks and other semantic analysis.


@v_args(meta=True)
class AbstractSyntaxTreeTransformer(BaseTransformer):
    """
    Pass 1: parse-tree → raw abstract syntax tree tokens, with no semantic validation.

    Responsibilities:
      - Build AST nodes for all top-level declarations.
      - Preserve dimension expressions in DimensionDeclaration.dimension_expression.
      - Do NOT:
          * check declaration order,
          * check that dimensions / categories / domains exist,
          * check category coverage or uniqueness,
          * check for duplicate names.
    """

    def __init__(self, *, file_path: Path, diagnostics: DiagnosticBag):
        super().__init__(file_path=file_path)
        self.diagnostics = diagnostics if diagnostics is not None else DiagnosticBag()

    # ---------- leaf grammar rules ----------

    def label(self, meta: Any, children: List[Token]) -> StringWithPosition:
        """
        ### Overview

        Label string handler.

        ### Returns

        A tuple of the label string and its source position.
        """
        assert len(children) == 1, f"Expected one label but found {len(children)}"
        token = children[0]
        return ast.literal_eval(token.value), symphony_position(self.file_path, meta)

    def documentation(self, meta: Any, children: List[Token]) -> StringWithPosition:
        """
        ### Overview
        Documentation Markdown handler.

        ### Returns

        A tuple of the documentation string and its source position.
        """
        assert len(children) == 1

        # strip leading and trailing """ of TRIPLE_STRING
        text: str = children[0].value[3:-3]

        # Remove leading and trailing whitespace/newlines
        text = text.strip()

        return (text, symphony_position(self.file_path, meta))

    def name_list(self, meta: Any, children: List[Token]) -> TypedList:
        """
        ### Overview

        A tuple with "list" in the first position and the tuple of name tokens in the second position.

        e.g.

        ```python
        ("list", [Token('NAME', 'red'), Token('NAME', 'green'), Token('NAME', 'blue')])
        ```
        """
        return ("list", list(children))

    def member_list(self, meta: Any, children: List[Any]) -> TypedList:
        """
        ### Overview

        Extract the list of member names from the member_list rule.

        This does nothing because what we need is created by name_list already.

        ### Returns

        A tuple with "list" in the first position and the list of members in the second position.
        """
        # position = symphony_position(file_path=self.file_path, token_or_meta=meta)
        for child in children:
            if isinstance(child, tuple) and child[0] == "list":
                return child
        raise AssertionError("member_list did not contain a list term")

    # ---------- declaration rules ----------
    def get_name(self, token: Token) -> str:
        """
        ### Overview

        Extract name from a NAME token.

        ### Exceptions
        Raises an assertion error if the token is not a NAME token.
        """
        assert (
            isinstance(token, Token) and token.type == "NAME"
        ), "Expected a NAME token"
        return token.value

    def get_label(self, label_with_position: StringWithPosition) -> str:
        """
        ### Overview

        Extract label string generated by the `label` grammar rule.

        ### Exceptions
        Raises an assertion error if the label child is not a string.
        """
        assert isinstance(label_with_position, tuple) and isinstance(
            label_with_position[0], str
        ), "Expected a label string"
        return label_with_position[0]

    def member_declaration(self, meta: Any, children: List[Any]) -> MemberDeclaration:
        """
        ### Overview

        Member declaration handler.
        """
        position: SourcePosition = symphony_position(
            file_path=self.file_path, token_or_meta=meta
        )
        name: str = self.get_name(children[1])
        label: str = self.get_label(children[2])
        documentation, list_term = self._pick_doc_and_list(children[3:])

        return MemberDeclaration(
            position=position,
            name=name,
            label=label,
            documentation=documentation,
        )

    def category_declaration(
        self, meta: Any, children: List[Any]
    ) -> CategoryDeclaration:
        """
        ### Overview

        Category declaration handler.
        """
        position: SourcePosition = symphony_position(
            file_path=self.file_path, token_or_meta=meta
        )
        name: str = self.get_name(children[1])
        label: str = children[2][0]
        documentation, list_term = self._pick_doc_and_list(children[3:])

        members: List[str] = []
        if list_term is not None:
            tag, payload = list_term
            if tag != "list":
                raise ValueError("Internal error: expected list term for category.")
            tokens: Iterable[Token] = payload
            members = [tok.value for tok in tokens]

        return CategoryDeclaration(
            position=position,
            name=name,
            label=label,
            documentation=documentation,
            members=members,
        )

    def dimension_declaration(
        self, meta: Any, children: List[Any]
    ) -> DimensionDeclaration:
        """
        ### Overview

        Dimension declaration handler.
        """
        position: SourcePosition = symphony_position(
            file_path=self.file_path, token_or_meta=meta
        )
        name: str = self.get_name(token=children[1])
        label: str = self.get_label(label_with_position=children[2])
        documentation, list_term = self._pick_doc_and_list(children[3:])
        logging.debug(list_term)
        exit("Done")

        members: List[str] = []
        if list_term is not None:
            tag, payload = list_term
            if tag != "list":
                raise ValueError("Internal error: expected list term for category.")
            tokens: Iterable[Token] = payload
            members = [tok.value for tok in tokens]

        return DimensionDeclaration(
            position=position,
            name=name,
            label=label,
            documentation=documentation,
            members=members,
        )

    # ---------- top-level rule ----------

    def start(self, meta: Any, children: List[AnyDeclaration]) -> Modules:
        """
        Top-level grammar rule: wrap all declarations into a Program.
        No semantic checks here.
        """
        return Module(declarations=children)

    @staticmethod
    def _pick_doc_and_list(
        extra_items: List[Any],
    ) -> Tuple[Optional[StringWithPosition], Optional[TypedList]]:
        """
        ### Overview

        Extract documentation from remaining list terms in a declaration.

        ### Arguments

        - `extra_items: List[Any]`: The list of extra items to search.

        ### Returns

        - `Tuple[Optional[Documentation], Optional[DimensionTerm]]`: The extracted documentation and list term.

        """

        documentation: Optional[StringWithPosition] = None
        list_term: Optional[TypedList] = None

        for item in extra_items:
            if not isinstance(item, tuple):
                continue
            if list_term is None and len(item) >= 1 and item[0] == "list":
                list_term = item  # type: ignore[assignment]
            elif documentation is None and len(item) == 2 and isinstance(item[0], str):
                documentation = item  # type: ignore[assignment]

        return documentation, list_term


# ---------- Create the abstract syntax tree for the whole model ---------


def load_modules(root_file_path: Path) -> SymphonyFiles:
    """
    ### Overview

    Load a complete Symphony model from the given root file path,
    processing all included files recursively.

    ### Arguments

    - `root_file_path`: Path to the root Symphony file.

    """
    loader_result: LoaderResult = Loader().load_symphony_files(
        root_file_path=root_file_path
    )

    if loader_result.diagnostics.has_errors():
        report_diagnostics(loader_result.diagnostics.diagnostics)
        raise SymphonyDiagnosticsException(loader_result.diagnostics.diagnostics)

    model: Modules = Modules()
    diagnostics: DiagnosticBag = loader_result.diagnostics
    for symphony_file in loader_result.symphony_files.file_list:
        try:
            module: Module = AbstractSyntaxTreeTransformer(
                file_path=symphony_file.file_path,
                diagnostics=loader_result.diagnostics,
            ).transform(symphony_file.tree)
        except UnexpectedInput as err:
            assert (
                False
            ), f"Failed to analyse declaration in {symphony_file.file_path}\n"
        model.add(module)
    return model

@dataclass(frozen=True)
class ASTLoaderResult:
    """
    This is the result returned by the abstract syntax tree loader.

    It supports both the loaded modules and any diagnostics encountered.
    """
    modules: Modules
    diagnostics: DiagnosticBag

def load_modules(loader_result: LoaderResult) -> ASTLoaderResult:
    """
    ### Overview

    Load a complete Symphony model from the given Lark parse trees.

    ### Arguments

    - `symphony_files`: The SymphonyFiles object containing all the Lark parse trees for the files that
    will be loaded into the abstract syntax tree.

    """

    modules: list[Module] = []
    diagnostics: DiagnosticBag = loader_result.diagnostics
    for symphony_file in loader_result.symphony_files.file_list:
        try:
            module: Module = AbstractSyntaxTreeTransformer(
                file_path=symphony_file.file_path,
                diagnostics=diagnostics,
            ).transform(symphony_file.tree)
            modules.append(module)
        except UnexpectedInput as err:
            # The module does not get added to the set of modules because it could not be transformed into an AST.
            # TODO: improve error reporting here - check for how this should be done to respond to error details in transformer.
            diagnostics.diagnostics.add(
                Diagnostic(
                    code=errors.syntax_error,
                    severity=DiagnosticSeverity.error,
                    message=f"Failed to parse Symphony file. {err}",
                    primary_label=DiagnosticLabel(
                        position=SourcePosition(file_path=symphony_file.file_path, line=1, column=1),
                        message="Symphony error occurred here.",
                        is_primary=True,
                    ),
                    help_text="Check for errors near this location.",
                )
            )

    return ASTLoaderResult(
        modules=Modules(modules=tuple(modules)),
        diagnostics=diagnostics,
    )